name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore OnlineStore.sln
      working-directory: ./
    - name: Build
      run: dotnet build OnlineStore.sln --configuration Release --no-restore
    - name: Test OnlineStore.API.Customers.Tests
      run: dotnet test OnlineStore.API.Customers.Tests --no-restore --verbosity normal
    - name: Test OnlineStore.API.Orders.Tests
      run: dotnet test OnlineStore.API.Orders.Tests --no-restore --verbosity normal
    - name: Test OnlineStore.API.Orders.Tests
      run: dotnet test OnlineStore.API.Orders.Tests --no-restore --verbosity normal
    - name: Test OnlineStore.API.Products.Tests
      run: dotnet test OnlineStore.API.Products.Tests --no-restore --verbosity normal
