name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore Customers
      run: dotnet restore OnlineStore.API.Customers
    - name: Restore Orders
      run: dotnet restore OnlineStore.API.Orders
    - name: Restore Products
      run: dotnet restore OnlineStore.API.Products
    - name: Restore Search
      run: dotnet restore OnlineStore.API.Search
    - name: Build
      run: dotnet build OnlineStore.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
